/* MakerGear defines*/

#define MAKERGEAR_MODEL "M3 Demeter"
#define MAKERGEAR_AUTHOR "MG |Scott, Josh, David, Kyle"

#define M2_X_PULLEY_STEPS 88.8 
#define M3_X_PULLEY_STEPS 80.1

#define M2_Y_PULLEY_STEPS 88.8
#define M3_Y_PULLEY_STEPS 80.1

#define M2_Z_STEPS 1007.7
#define M3_Z_STEPS 1007.7

#define M2_X_MIN 0
#define M3_X_MIN -4
#define M2_Y_MIN 0
#define M3_Y_MIN 0
#define M2_Z_MIN -1
#define M3_Z_MIN -1

#define M2_X_MAX 205
#define M3_X_MAX 220
#define M2_Y_MAX 255
#define M3_Y_MAX 253
#define M2_Z_MAX 200
#define M3_Z_MAX 210

#define X_MOTOR_CURRENT 100
#define Y_MOTOR_CURRENT 100
#define Z_MOTOR_CURRENT 190
#define E_MOTOR_CURRENT 95

#define RAMBO_SHIELD_11 11
#define RAMBO_SHIELD_12 12
#define RAMBO_SHIELD_13 13
#define RAMBO_SHIELD_14 14

#define M2_PRINTED_FILAMENT_DRIVE_DIRECTION true
#define M3_PRINTED_FILAMENT_DRIVE_DIRECTION false
#define M3_METAL_FILAMENT_DRIVE_DIRECTION true


#define M2_X_DIRECTION true
#define M3_X_DIRECTION false


#define M2_Y_DIRECTION false
#define M3_Y_DIRECTION true


#define M2_Z_DIRECTION false
#define M3_Z_DIRECTION true

#define ONE_X_CARRIAGE 1
#define TWO_X_CARRIAGE 2


#define PRINTED_FILAMENT_MOTOR_STEPS 471.5
#define METAL_FILAMENT_MOTOR_STEPS 81.0

#define PRINTED_FILAMENT_MOTOR_CURRENT 95
#define METAL_FILAMENT_MOTOR_CURRENT 135

#define ENDSTOPS_NC false
#define ENDSTOPS_NO true

#define SECOND_X_PWM 100

#define AUTO_REWRITE_EEPROM	false


#define CONF_X_PULLEY_STEPS  			M3_X_PULLEY_STEPS
#define CONF_Y_PULLEY_STEPS  			M3_Y_PULLEY_STEPS
#define CONF_Z_STEPS  					M3_Z_STEPS
#define CONF_FILAMENT_MOTOR_STEPS  		PRINTED_FILAMENT_MOTOR_STEPS

#define CONF_SHIELD    					RAMBO_SHIELD_14
#define CONF_CARRIAGE  					ONE_X_CARRIAGE

#define CONF_ENDSTOPS  					ENDSTOPS_NC
#define CONF_X_DIRECTION  				M3_X_DIRECTION
#define CONF_Y_DIRECTION  				M3_Y_DIRECTION
#define CONF_Z_DIRECTION  				M3_Z_DIRECTION
#define CONF_EXTRUDER_DIRECTION  		M3_PRINTED_FILAMENT_DRIVE_DIRECTION
#define CONF_EXTRUDER_MOTOR_CURRENT 	PRINTED_FILAMENT_MOTOR_CURRENT
#define CONF_X_MAX 						M3_X_MAX
#define CONF_Y_MAX 						M3_Y_MAX
#define CONF_Z_MAX					 	M3_Z_MAX
#define CONF_X_MIN						M3_X_MIN
#define CONF_Y_MIN 						M3_Y_MIN
#define CONF_Z_MIN 						M3_Z_MIN

