/* MakerGear defines*/

#define MAKERGEAR_MODEL "M3 Demeter"
#define MAKERGEAR_AUTHOR "MG |Scott, Josh, Kyle"

#define M2_X_PULLEY 88.8 
#define M3_X_PULLEY 80.1

#define M2_Y_PULLEY 88.8
#define M3_Y_PULLEY 80.1


#define M2_X_MAX 205
#define M3_X_MAX 220

#define M2_Y_MAX 255
#define M3_Y_MAX 253

#define M2_Z_MAX 200
#define M3_Z_MAX 210


#define RAMBO_SHIELD_11 11
#define RAMBO_SHIELD_12 12
#define RAMBO_SHIELD_13 13
#define RAMBO_SHIELD_14 14

#define M2_PRINTED_FILAMENT_DRIVE true
#define M3_PRINTED_FILAMENT_DRIVE_DIRECTION false


#define M2_X_DIRECTION true
#define M3_X_DIRECTION false


#define M2_Y_DIRECTION false
#define M3_Y_DIRECTION true


#define M2_Z_DIRECTION false
#define M3_Z_DIRECTION true

#define ONE_X_CARRIAGE 1
#define TWO_X_CARRIAGE 2

#define GEARBOX_FILAMENT_MOTOR 471.5
#define DIRECT_FILAMENT_MOTOR 88.1

#define ENDSTOPS_NC false
#define ENDSTOPS_NO true

#define SECOND_X_PWM 90

#define AUTO_REWRITE_EEPROM	false

#define CONF_X_PULLEY  			M3_X_PULLEY
#define CONF_Y_PULLEY  			M3_Y_PULLEY
#define CONF_SHIELD    			RAMBO_SHIELD_13
#define CONF_CARRIAGE  			ONE_X_CARRIAGE
#define CONF_FILAMENT_MOTOR  	GEARBOX_FILAMENT_MOTOR
#define CONF_ENDSTOPS  			ENDSTOPS_NC
#define CONF_X_DIRECTION  		M3_X_DIRECTION
#define CONF_Y_DIRECTION  		M3_Y_DIRECTION
#define CONF_Z_DIRECTION  		M3_Z_DIRECTION
#define CONF_EXTRUDER0_DIRECTION  M3_PRINTED_FILAMENT_DRIVE_DIRECTION
#define CONF_X_MAX M3_X_MAX
#define CONF_Y_MAX M3_Y_MAX
#define CONF_Z_MAX M3_Z_MAX
